"""indexes from Schema.md section 5

Revision ID: feb7e554fd31
Revises: 00d3e0b26a18
Create Date: 2026-10-08 16:01:38.447072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb7e554fd31'
down_revision: Union[str, Sequence[str], None] = '00d3e0b26a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_agent_traces_decision', 'agent_traces', ['decision_id', 'step_at'], unique=False)
    op.create_index('uq_approvals_decision_user', 'approvals', ['decision_id', 'approved_by'], unique=True)
    op.create_index('idx_batches_safety_status', 'batches', ['safety_status'], unique=False)
    op.create_index('idx_decisions_status', 'decisions', ['status'], unique=False)
    op.create_index('idx_demand_location_commodity', 'demand_records', ['location_id', 'commodity_id'], unique=False)
    op.create_index('idx_kpi_name_scope', 'kpi_snapshots', ['kpi_name', 'scope', 'computed_at'], unique=False)
    op.create_index('idx_supply_location_commodity', 'supply_records', ['location_id', 'commodity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_supply_location_commodity', table_name='supply_records')
    op.drop_index('idx_kpi_name_scope', table_name='kpi_snapshots')
    op.drop_index('idx_demand_location_commodity', table_name='demand_records')
    op.drop_index('idx_decisions_status', table_name='decisions')
    op.drop_index('idx_batches_safety_status', table_name='batches')
    op.drop_index('uq_approvals_decision_user', table_name='approvals')
    op.drop_index('idx_agent_traces_decision', table_name='agent_traces')
    # ### end Alembic commands ###
